apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: zone-ingress
  namespace: onlineboutique
spec:
  template:
    spec:
      backend:
        serviceName: zone-mcs
        servicePort: 8080
