--- 
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata: 
  name: zone-mcs
  namespace: onlineboutique
spec: 
  template: 
    spec: 
      ports: 
        - 
          name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector: 
        app: frontend
